jobs:
- job_id: live_fixtures_all
  type: live_loop
  enabled: false
  priority: CRITICAL
  endpoint: /fixtures
  params:
    live: all
  interval:
    type: interval
    seconds: 15
  target_layer: raw+core+mart
  filters:
    tracked_leagues:
    - 39
    - 40
    - 41
    - 42
    - 61
    - 62
    - 78
    - 79
    - 80
    - 88
    - 94
    - 95
    - 106
    - 111
    - 112
    - 121
    - 135
    - 136
    - 140
    - 141
    - 144
    - 145
    - 162
    - 179
    - 180
    - 183
    - 184
    - 185
    - 188
    - 197
    - 203
    - 204
    - 207
    - 208
    - 210
    - 218
    - 219
    - 241
    - 242
    - 262
    - 271
    - 274
    - 276
    - 281
    - 283
    - 286
    - 290
    - 291
    - 296
    - 302
    - 303
    - 308
    - 312
    - 315
    - 332
    - 333
    - 344
    - 345
    - 370
    - 380
    - 381
    - 390
    - 393
    - 396
    - 399
    - 407
    - 408
    - 419
    - 492
    - 516
    - 570
    - 585
    - 677
    - 701
    - 705
    - 828
    - 848
    - 865
    - 871
    - 967
    - 976
    - 1059
    - 1168
  coverage_target:
    endpoint: /fixtures
    live: true
    max_lag_minutes: 1
